version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/TaskManager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kmw@0818
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: task-manager
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: TaskManager
      MYSQL_ROOT_PASSWORD: kmw@0818
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
